name: Build EC2

on:
    push:
      branches: [doom]
    workflow_dispatch: # Trigger manually from the Actions tab      

jobs:
 build_droplet:
   runs-on: ubuntu-latest
   outputs:
    id: ${{ steps.ec2Outputs.outputs.id}}
    public_ip: ${{ steps.ec2Outputs.outputs.ipv4}}

   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
        
     - name: Install Terraform
       uses: hashicorp/setup-terraform@v3
       with:
        terraform_version: 1.10.2
    
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: east-us-1
       
     - name: Terraform Init
       run: |
        terraform init \
          -backend-config="access_key=${{ secrets.DO_SPACES_ACCESS_KEY }}" \
          -backend-config="secret_key=${{ secrets.DO_SPACES_SECRET_KEY }}"
    
     - name: Terraform Plan
       run: terraform plan -out=tfplan

     - name: Terraform Apply
       id: apply
       run: |
         terraform apply -auto-approve tfplan \
       working-directory: ./terraform

     - name: Get EC2 Outputs
       id: ec2Outputs
       run: |
        EC2_INFO=$(terraform output -json ec2_info)
        echo "id=$(echo $EC2_INFO| jq -r '.id')" >> $GITHUB_OUTPUT
        echo "public_ip=$(echo $EC2_INFO | jq -r '.ipv4')" >> $GITHUB_OUTPUT
       working-directory: ./terraform  

    
